---
# tasks file for jenkins
- name: Import GPG key
  rpm_key:
    state: present
    key: http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key

- name: Create jenkins repository
  yum_repository:
      name: jenkins
      description: jenkins repository
      baseurl: http://pkg.jenkins.io/redhat
      enabled: yes 
      gpgcheck: yes 

- name:  Install Java 8
  yum: 
    name: java-1.8.0-openjdk.x86_64
    state: absent

- name:  Install Java 8
  yum: 
    name: java-1.8.0-openjdk-devel.x86_64
    state: present

#sudo yum install -y java-1.8.0-openjdk-devel.x86_64
- name: Install git
  yum:
    name: git
    state: present

- name: Set Java 8 as the default
  command: /usr/sbin/alternatives --set java /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-0.amzn2.x86_64/jre/bin/java

- name: Install Jenkins
  yum:
    name: jenkins
    state: present

- name: Start the jenkins service and ensure that it gets started on system boot
  service:
      name: jenkins
      state: started
      enabled: yes

#- name: Install maven
#  become: yes
#  #apt: pkg=maven state=latest update_cache=yes cache_valid_time=3600
#  get_url: url=http://apache.claz.org/maven/maven-3/3.1.1/binaries/apache-maven-3.1.1-bin.tar.gz dest=/tmp/apache-maven-3.1.1-bin.tar.gz
#- name: Untar maven
#  shell: chdir=/tmp creates=/opt/apache-maven-3.1.1 tar -zxf apache-maven-3.1.1-bin.tar.gz -C /opt
##- name: Update path for maven
#  #shell: export PATH=/opt/apache-maven-3.1.1/bin/:$PATH
#- shell: echo PATH is $PATH
#  environment:
#    #JAVA_HOME: /usr/java/jre1.8.0_51
#    PATH: $PATH:/opt/apache-maven-3.1.1/bin/
#    register: shellout
#- debug: var=shellout


